name = "CountingChambers"
uuid = "23b3ee6f-a072-41d8-ada8-267420d58637"
authors = ["tbrysiewicz <taylorbrysiewicz@gmail.com>"]
version = "0.2.3"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Hecke = "3e1990a7-5d81-5526-99ce-9ba3ff248f21"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
SaferIntegers = "88634af6-177f-5301-88b8-7819386cfa38"

[compat]
julia = "1"
Combinatorics = "1.0.0 - 2.0.0"
GAP = "0.12 - 0.16"
Hecke = "0.30 - 0.50"
Nemo = "0.40 - 0.60"
SaferIntegers = "3.0.0 - 4.0.0"
